version: "3.3"

services:
  web:
    build:
      context: ./projetoPhp
      dockerfile: Dockerfile
    volumes:
      - ./projetoPHP:/var/www/html
    networks:
      - frontend
      - backend
    ports:
      - 80:80
  db:
    image: mysql:8
    depends_on:
      - web
    networks:
      - backend
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
networks:
  frontend:
  backend: